/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 23-sept.-2020 5:54:54 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `categoria` CASCADE
;

DROP TABLE IF EXISTS `empresa` CASCADE
;

DROP TABLE IF EXISTS `marca` CASCADE
;

DROP TABLE IF EXISTS `producto` CASCADE
;

/* Create Tables */

CREATE TABLE `categoria` (
    `id` INT NOT NULL,
    `descripcion` VARCHAR(100) NULL COMMENT 'Almacena la descripción del producto',
    `estado` VARCHAR(1) NULL COMMENT 'Define si la categoria esta activa o no',
    CONSTRAINT `PK_categoria` PRIMARY KEY (`id` ASC)
)  COMMENT='Almacena la información de las categorias de los productos de la empresa'

;

CREATE TABLE `empresa` (
    `id` INT NOT NULL,
    `nombre` VARCHAR(100) NULL COMMENT 'Almacena el nombre de la empresa',
    `quienessomos` VARCHAR(500) NULL COMMENT 'Almacena la información de la empresa',
    `emailcontacto` VARCHAR(50) NULL COMMENT 'Almacena el email al cual se enviaran los contactos',
    `direccion` VARCHAR(200) NULL COMMENT 'Almacena la dirección de',
    `telefonocontacto` VARCHAR(20) NULL,
    `facebook` VARCHAR(100) NULL,
    `twitter` VARCHAR(100) NULL,
    `instagram` VARCHAR(100) NULL,
    CONSTRAINT `PK_empresa` PRIMARY KEY (`id` ASC)
)  COMMENT='Almacena la información de la empresa.  Incluye todo lo referente a la configuración de la empresa.'

;

CREATE TABLE `marca` (
    `id` INT NOT NULL,
    `nombre` VARCHAR(100) NULL COMMENT 'Registra el nombre de la empresa',
    `descripcion` VARCHAR(500) NULL COMMENT 'Registra información de la descripción de la marca',
    CONSTRAINT `PK_marca` PRIMARY KEY (`id` ASC)
)  COMMENT='Almacena la información de las marcas de los productos'

;

CREATE TABLE `producto` (
    `id` INT NOT NULL,
    `referencia` VARCHAR(20) NULL COMMENT 'Referencia de los productos',
    `nombre` VARCHAR(100) NULL COMMENT 'Nombre del producto',
    `descripcioncorta` VARCHAR(250) NULL COMMENT 'Una descripcion corta del producto',
    `detalle` TEXT NULL COMMENT 'Detalle extenso de la información del producto',
    `valor` DECIMAL(10 , 2 ) NULL COMMENT 'Precio del producto',
    `palabrasclave` VARCHAR(100) NULL COMMENT 'Palabras claves del producto ',
    `estado` VARCHAR(1) NULL COMMENT 'Estado del producto',
    `categoria_id` INT NULL,
    `marca_id` INT NULL,
    CONSTRAINT `PK_producto` PRIMARY KEY (`id` ASC)
)  COMMENT='Almacena la información del producto'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `producto` 
 ADD INDEX `IXFK_producto_categoria` (`categoria_id` ASC)
;

ALTER TABLE `producto` 
 ADD INDEX `IXFK_producto_marca` (`marca_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `producto` 
 ADD CONSTRAINT `FK_producto_categoria`
	FOREIGN KEY (`categoria_id`) REFERENCES `categoria` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `producto` 
 ADD CONSTRAINT `FK_producto_marca`
	FOREIGN KEY (`marca_id`) REFERENCES `marca` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
